### ISSUE TITLE
Run tests on OS X

### ISSUE THREAD

**Issue by whtsky** [whtsky/WeRoBot#102]

**Comment by helloqiu** [comment]
```
======================================================================
ERROR: test_session.test_session
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/helloqiu/python/werobot/.eggs/nose-1.3.7-py2.7.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/helloqiu/python/werobot/werobot/tests/test_session.py", line 60, in test_session
    filestorage.FileStorage(),
  File "/Users/helloqiu/python/werobot/werobot/session/filestorage.py", line 20, in __init__
    self.db = dbm.open(filename, "c")
  File "/usr/local/var/pyenv/versions/2.7.9/lib/python2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
error: (35, 'Resource temporarily unavailable')

----------------------------------------------------------------------
Ran 26 tests in 0.082s

FAILED (errors=2)
```
