### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by weberwang** [whtsky/WeRoBot#151]
Ubuntu 14.04 64位
python3.5.2
测试脚本
`@robot.handler
    def echo(message):
        return 'Hello World!'`
出现MemoryError
本地测试`utils.to_binary(int(time.time()))`
`Traceback (most recent call last):
  File "test.py", line 22, in <module>
    to_binary(int(time.time()))
  File "C:\Python34\lib\site-packages\werobot-1.0.0-py3.4.egg\werobot\utils.py", line 45, in to_binary
    return six.binary_type(value)
MemoryError`

**Comment by weberwang** [comment]
to_binary改成to_text即可兼容2/3版本
