### ISSUE TITLE
Reply Image error

### ISSUE THREAD

**Issue by rikewang** [whtsky/WeRoBot#224]
what's wrong??

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/lib/python2.7/site-packages/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/usr/lib64/python2.7/site-packages/werobot/contrib/bottle.py", line 62, in werobot_view
    return robot.get_encrypted_reply(message)
  File "/usr/lib64/python2.7/site-packages/werobot/robot.py", line 358, in get_encrypted_reply
    return reply.render()
  File "/usr/lib64/python2.7/site-packages/werobot/replies.py", line 57, in render
    return to_text(self.TEMPLATE.format(**self._args))
KeyError: u'target'

--------------------------

import werobot
from werobot.replies import ImageReply
from werobot.client import Client

robot = werobot.WeRoBot(token='1x')

@robot.text
def txt_handle(message):
    return 'Hello World!'

@robot.image
def img_handle(message):
    # print dir(message)
    res = robot.client.download_media(message.MediaId)
    print dir(res)
    return ImageReply(media_id=message.MediaId)

robot.config['HOST'] = '0.0.0.0'
robot.config['PORT'] = 80
robot.config['APP_ID'] = 'x'
robot.config['APP_SECRET'] = 'x'
robot.config['ENCODING_AES_KEY'] = 'x'

robot.run()

**Comment by whtsky** [comment]
ImageReply(message=message, media_id=message.NediaId)
