### ISSUE TITLE
新手来问个问题，请楼主大神帮帮忙

### ISSUE THREAD

**Issue by cnchenji** [whtsky/WeRoBot#225]
我在阿里云服务器上配置的nginx环境，其他都配置好了。微信公众号那边token验证也都通过了。试了试公众号发信息过去，并未响应hello world（这个是参照例子搞的），后来去查日志文件，报错情况如下：

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/lib/python2.7/site-packages/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/usr/lib64/python2.7/site-packages/werobot/contrib/bottle.py", line 62, in werobot_view
    return robot.get_encrypted_reply(message)
  File "/usr/lib64/python2.7/site-packages/werobot/robot.py", line 350, in get_encrypted_reply
    reply = self.get_reply(message)
  File "/usr/lib64/python2.7/site-packages/werobot/robot.py", line 322, in get_reply
    session_storage = self.session_storage
  File "/usr/lib64/python2.7/site-packages/werobot/utils.py", line 42, in wrapped_func
    setattr(self, prop_name, method(self, *args, **kwargs))
  File "/usr/lib64/python2.7/site-packages/werobot/robot.py", line 116, in session_storage
    self.config["SESSION_STORAGE"] = SQLiteStorage()
  File "/usr/lib64/python2.7/site-packages/werobot/session/sqlitestorage.py", line 27, in __init__
    self.db = sqlite3.connect(filename, check_same_thread=False)
OperationalError: unable to open database file

求大神帮看看可能是什么环节出了问题，感谢。

**Comment by helloqiu** [comment]
用的什么 WSGI Server？
运行用户是否有权限读写 sqlite 文件？
建议试一试在用 SqliteStorage 的时候把 filename 换成有权限的绝对路径。
@cnchenji

**Comment by cnchenji** [comment]
@helloqiu    感谢大神，我用的gunicorn.  参考网上的例子写了个最简单的代码如下，就报了上面的错：
基本应答helloworld代码 in app.py:

import werobot
robot = werobot.WeRoBot(token='xxxx')

@robot.handler
def echo(message): 
    return 'Hello World!'

robot.run(server="gunicorn", port=8000)

**Comment by cnchenji** [comment]
我暂时把sessions的存储功能关闭了，给公众号发信息是能得到hello world的响应的。

**Comment by helloqiu** [comment]
感觉是权限问题，我没有复现（
建议检查权限，或者
> 建议试一试在用 SqliteStorage 的时候把 filename 换成有权限的绝对路径。
