### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by sgyyamn** [whtsky/WeRoBot#251]
Traceback (most recent call last):
  File "/data1/www/htdocs/813/everything123/1/index.wsgi", line 2, in <module>
    from robot import robot
  File "/data1/www/htdocs/813/everything123/1/robot.py", line 10, in <module>
    robot = werobot.WeRoBot('mytoken')
AttributeError: 'module' object has no attribute 'WeRoBot'

**代码是sae配置例程里的**
import os
import sys
root = os.path.dirname(__file__)
sys.path.insert(0, os.path.join(root, 'site-packages'))
import werobot
robot = werobot.WeRoBot('mytoken')
@robot.handler
def echo(message):
    return 'Hello World!'

**Comment by sgyyamn** [comment]
sorry 眼花了

**Comment by sgyyamn** [comment]
robot = werobot.WeRoBot(token='mytoken')  提示AttributeError: 'module' object has no attribute 'WeRoBot'
