### ISSUE TITLE
pip install werobot 出错

### ISSUE THREAD

**Issue by yuangezhizao** [whtsky/WeRoBot#268]
请问该如何解决？
```
C:\>pip install werobot
Collecting werobot
  Using cached WeRoBot-1.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Couldn't find index page for 'pytest-runner' (maybe misspelled?)
    No local packages or download links found for pytest-runner
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\admini~1\appdata\local\temp\2\pip-build-gycb1a\werobot\setu
p.py", line 57, in <module>
        package_data={'werobot': ['contrib/*.html']}
      File "C:\Python27\lib\distutils\core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "C:\Python27\lib\site-packages\setuptools\dist.py", line 260, in __in
it__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "C:\Python27\lib\site-packages\setuptools\dist.py", line 284, in fetc
h_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 850,
in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 1122,
 in best_match
        return self.obtain(req, installer)
      File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 1134,
 in obtain
        return installer(requirement)
      File "C:\Python27\lib\site-packages\setuptools\dist.py", line 327, in fetc
h_build_egg
        return cmd.easy_install(req)
      File "C:\Python27\lib\site-packages\setuptools\command\easy_install.py", l
ine 434, in easy_install
        self.local_index
      File "C:\Python27\lib\site-packages\setuptools\package_index.py", line 475
, in fetch_distribution
        return dist.clone(location=self.download(dist.location, tmpdir))
    AttributeError: 'NoneType' object has no attribute 'clone'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\admini~1
\appdata\local\temp\2\pip-build-gycb1a\werobot\

```

**Comment by whtsky** [comment]
升级一下 pip 和 setuptools 试试
`pip install -U pip setuptools`
