### ISSUE TITLE
关于 pymysql.err.OperationalError: (2014, 'Command Out of Sync') 的报错

### ISSUE THREAD

**Issue by yuangezhizao** [whtsky/WeRoBot#271]
之前在用 py 2，花了两天时间换到了 py 3，反复试了好几次（重启），一直报这个错误，请问该如何解决，谢谢
```
ERROR:WeRoBot:Catch an exception\r
Traceback (most recent call last):\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\werobot\\robot.py", line 401, in get_reply\r
    session_storage[id] = session\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\werobot\\session\\__init__.py", line 15, in __setitem__\r
    self.set(id, session)\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\werobot\\session\\mysqlstorage.py", line 82, in set\r
    self.conn.commit()\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\pymysql\\connections.py", line 781, in commit\r
    self._read_ok_packet()\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\pymysql\\connections.py", line 762, in _read_ok_packet\r
    raise err.OperationalError(2014, "Command Out of Sync")\r
pymysql.err.OperationalError: (2014, 'Command Out of Sync')
\r
WARNING:WeRoBot:No handler responded message <werobot.messages.messages.TextMessage object at 0x0000000006704C50>\r
[2018-01-20 21:27:09,480] ERROR in app: Exception on /robot/ [POST]\r
Traceback (most recent call last):\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\flask\\app.py", line 1982, in wsgi_app\r
    response = self.full_dispatch_request()\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\flask\\app.py", line 1614, in full_dispatch_request\r
    rv = self.handle_user_exception(e)\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\flask\\app.py", line 1517, in handle_user_exception\r
    reraise(exc_type, exc_value, tb)\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\flask\\_compat.py", line 33, in reraise\r
    raise value\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\flask\\app.py", line 1612, in full_dispatch_request\r
    rv = self.dispatch_request()\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\flask\\app.py", line 1598, in dispatch_request\r
    return self.view_functions[rule.endpoint](**req.view_args)\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\werobot\\contrib\\flask.py", line 59, in werobot_view\r
    response = make_response(robot.get_encrypted_reply(message))\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\werobot\\robot.py", line 416, in get_encrypted_reply\r
    reply = self.get_reply(message)\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\werobot\\robot.py", line 393, in get_reply\r
    session = session_storage[id]\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\werobot\\session\\__init__.py", line 12, in __getitem__\r
    return self.get(id)\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\werobot\\session\\mysqlstorage.py", line 66, in get\r
    cur.execute("SELECT value FROM WeRoBot WHERE id=%s LIMIT 1;", (id,))\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\pymysql\\cursors.py", line 165, in execute\r
    result = self._query(query)\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\pymysql\\cursors.py", line 321, in _query\r
    conn.query(q)\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\pymysql\\connections.py", line 860, in query\r
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\pymysql\\connections.py", line 1061, in _read_query_result\r
    result.read()\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\pymysql\\connections.py", line 1356, in read\r
    self._read_result_packet(first_packet)\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\pymysql\\connections.py", line 1421, in _read_result_packet\r
    self._get_descriptions()\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\pymysql\\connections.py", line 1492, in _get_descriptions\r
    field = self.connection._read_packet(FieldDescriptorPacket)\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\pymysql\\connections.py", line 1017, in _read_packet\r
    packet = packet_type(buff, self.encoding)\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\pymysql\\connections.py", line 399, in __init__\r
    self._parse_field_descriptor(encoding)\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\pymysql\\connections.py", line 406, in _parse_field_descriptor\r
    self.catalog = self.read_length_coded_string()\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\pymysql\\connections.py", line 343, in read_length_coded_string\r
    length = self.read_length_encoded_integer()\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\pymysql\\connections.py", line 334, in read_length_encoded_integer\r
    return self.read_uint64()\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\pymysql\\connections.py", line 306, in read_uint64\r
    result = struct.unpack_from('<Q', self._data, self._position)[0]\r
struct.error: unpack_from requires a buffer of at least 8 bytes
\r
[2018-01-20 21:27:09,481] ERROR in app: Exception on /robot/ [POST]\r
Traceback (most recent call last):\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\flask\\app.py", line 1982, in wsgi_app\r
    response = self.full_dispatch_request()\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\flask\\app.py", line 1614, in full_dispatch_request\r
    rv = self.handle_user_exception(e)\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\flask\\app.py", line 1517, in handle_user_exception\r
    reraise(exc_type, exc_value, tb)\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\flask\\_compat.py", line 33, in reraise\r
    raise value\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\flask\\app.py", line 1612, in full_dispatch_request\r
    rv = self.dispatch_request()\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\flask\\app.py", line 1598, in dispatch_request\r
    return self.view_functions[rule.endpoint](**req.view_args)\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\werobot\\contrib\\flask.py", line 59, in werobot_view\r
    response = make_response(robot.get_encrypted_reply(message))\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\werobot\\robot.py", line 416, in get_encrypted_reply\r
    reply = self.get_reply(message)\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\werobot\\robot.py", line 393, in get_reply\r
    session = session_storage[id]\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\werobot\\session\\__init__.py", line 12, in __getitem__\r
    return self.get(id)\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\werobot\\session\\mysqlstorage.py", line 66, in get\r
    cur.execute("SELECT value FROM WeRoBot WHERE id=%s LIMIT 1;", (id,))\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\pymysql\\cursors.py", line 165, in execute\r
    result = self._query(query)\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\pymysql\\cursors.py", line 321, in _query\r
    conn.query(q)\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\pymysql\\connections.py", line 860, in query\r
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\pymysql\\connections.py", line 1061, in _read_query_result\r
    result.read()\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\pymysql\\connections.py", line 1356, in read\r
    self._read_result_packet(first_packet)\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\pymysql\\connections.py", line 1421, in _read_result_packet\r
    self._get_descriptions()\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\pymysql\\connections.py", line 1492, in _get_descriptions\r
    field = self.connection._read_packet(FieldDescriptorPacket)\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\pymysql\\connections.py", line 1017, in _read_packet\r
    packet = packet_type(buff, self.encoding)\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\pymysql\\connections.py", line 399, in __init__\r
    self._parse_field_descriptor(encoding)\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\pymysql\\connections.py", line 406, in _parse_field_descriptor\r
    self.catalog = self.read_length_coded_string()\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\pymysql\\connections.py", line 343, in read_length_coded_string\r
    length = self.read_length_encoded_integer()\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\pymysql\\connections.py", line 334, in read_length_encoded_integer\r
    return self.read_uint64()\r
  File "C:\\Users\\Administrator\\.virtualenvs\\APP-QaV1et56\\Lib\\site-packages\\pymysql\\connections.py", line 306, in read_uint64\r
    result = struct.unpack_from('<Q', self._data, self._position)[0]\r
struct.error: unpack_from requires a buffer of at least 8 bytes
\r
```

**Comment by helloqiu** [comment]
开了多线程吗？
如果是 pymysql 不是 thread safe 的，可以尝试给每个线程不同的 connection object。

**Comment by yuangezhizao** [comment]
用的 Flask，开了多线程模式，外面是 apache + mod_wgsi，现在关电脑了，明天改完就回复，谢谢

**Comment by yuangezhizao** [comment]
手机远程关了 Flask 的 threaded 模式，倒是没问题了
