### ISSUE TITLE
0.6.0版本部署SAE的问题  404  "/" not found

### ISSUE THREAD

**Issue by mitechen** [whtsky/WeRoBot#68]
按照[WeRoBot-SAE-demo](https://github.com/whtsky/WeRoBot-SAE-demo)上的方法部署到SAE,`saecloud install werobot`命令并没有把0.11.6版的bottle.py安装到site-packages/目录。由于SAE默认为bottle0.96。不支持 `@app.post('<t:path>')`这种写法,导致发生404错误。必须手动copy 0.11.6版本的bottle.py到工程目录。

**Comment by iammsan** [comment]
入门，也是SAE下部署的配置问题，暂时还没找到原因
在site-pacakages下cp了six和bottle，还是出错：
Traceback (most recent call last):
  File "/data1/www/htdocs/840/hellomypython/1/index.wsgi", line 9, in <module>
    from robot import robot
  File "/data1/www/htdocs/840/hellomypython/1/robot.py", line 17, in <module>
    robot.run()
  File "/data1/www/htdocs/840/hellomypython/1/site-packages/werobot/robot.py", line 306, in run
    self.wsgi.run(server=server, host=host, port=port)
AttributeError: 'Bottle' object has no attribute 'run'

**Comment by csufuyi** [comment]
改这一句
from werobot.robot import werobot
