### ISSUE TITLE
使用微信公众号调试页面采用加密模式报错

### ISSUE THREAD

**Issue by adrianzhang** [whtsky/WeRoBot#81]
在服务器上安装了CherryPy，WeRoBot，根据范例写了个简单的接口，收任何消息都回复个”你好“。

利用官方调试页面进行发消息调试，该页面有个模式选择，选择明文模式报错为请求失败；选择兼容模式可以得到返回的消息（XML格式，确实是服务器回复的“你好”，其他内容也都对），但提示Decrypt Fail!  ；选择安全模式则post data error,please check your server!  ,无返回。看了微信文档，兼容模式这种情况是可以运行的，只不过消息往来都是明文。由于自己编程水平不够，想问问是WeRoBot不支持加密还是我的用法不对？多谢指点。

官方调试页面：
https://mp.weixin.qq.com/debug/cgi-bin/apiinfo?t=index&type=%E6%B6%88%E6%81%AF%E6%8E%A5%E5%8F%A3%E8%B0%83%E8%AF%95&form=%E6%96%87%E6%9C%AC%E6%B6%88%E6%81%AF

选择安全模式，服务器上有错误日志如下：

2015-08-25 20:18:13 d7b6bcef Traceback (most recent call last):

2015-08-25 20:18:13 d7b6bcef   File "/usr/local/lib/python2.7/site-packages/bottle.py", line 862, in _handle

2015-08-25 20:18:13 d7b6bcef     return route.call(**args)

2015-08-25 20:18:13 d7b6bcef   File "/usr/local/lib/python2.7/site-packages/bottle.py", line 1732, in wrapper

2015-08-25 20:18:13 d7b6bcef     rv = callback(*a, **ka)

2015-08-25 20:18:13 d7b6bcef   File "/usr/local/lib/python2.7/site-packages/werobot/robot.py", line 278, in handle

2015-08-25 20:18:13 d7b6bcef     message = parse_user_msg(body)

2015-08-25 20:18:13 d7b6bcef   File "/usr/local/lib/python2.7/site-packages/werobot/parser.py", line 19, in parse_user_msg

2015-08-25 20:18:13 d7b6bcef     wechat_message["type"] = wechat_message.pop("MsgType").lower()

2015-08-25 20:18:13 d7b6bcef KeyError: 'MsgType'

**Comment by whtsky** [comment]
develop 分支的代码是支持加密的。等对 event 的支持完善一些之后 release 0.7 版本，不太急的话稍微等一下吧。
Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.0.64&pv=8.2]
On 周二, 8月 25, 2015 at 8:39 下午, whtsky/WeRoBot
<reply@reply.github.com>
wrote:
在服务器上安装了CherryPy，WeRoBot，根据范例写了个简单的接口，收任何消息都回复个”你好“。


利用官方调试页面进行发消息调试，该页面有个模式选择，选择明文模式报错为请求失败；选择兼容模式可以得到返回的消息（XML格式，确实是服务器回复的“你好”，其他内容也都对），但提示Decrypt
Fail! ；选择安全模式则post data error,please check your server!
,无返回。看了微信文档，兼容模式这种情况是可以运行的，只不过消息往来都是明文。由于自己编程水平不够，想问问是WeRoBot不支持加密还是我的用法不对？多谢指点。

官方调试页面：

https://mp.weixin.qq.com/debug/cgi-bin/apiinfo?t=indextype=%E6%B6%88%E6%81%AF%E6%8E%A5%E5%8F%A3%E8%B0%83%E8%AF%95&form=%E6%96%87%E6%9C%AC%E6%B6%88%E6%81%AF]

选择安全模式，服务器上有错误日志如下：

2015-08-25 20:18:13 d7b6bcef Traceback (most recent call last):

2015-08-25 20:18:13 d7b6bcef File
"/usr/local/lib/python2.7/site-packages/bottle.py", line 862, in _handle

2015-08-25 20:18:13 d7b6bcef return route.call(**args)

2015-08-25 20:18:13 d7b6bcef File
"/usr/local/lib/python2.7/site-packages/bottle.py", line 1732, in wrapper

2015-08-25 20:18:13 d7b6bcef rv = callback( a, * ka)

2015-08-25 20:18:13 d7b6bcef File
"/usr/local/lib/python2.7/site-packages/werobot/robot.py", line 278, in handle

2015-08-25 20:18:13 d7b6bcef message = parse_user_msg(body)

2015-08-25 20:18:13 d7b6bcef File
"/usr/local/lib/python2.7/site-packages/werobot/parser.py", line 19, in
parse_user_msg

2015-08-25 20:18:13 d7b6bcef wechat_message["type"] =
wechat_message.pop("MsgType").lower()

2015-08-25 20:18:13 d7b6bcef KeyError: 'MsgType'

**Comment by adrianzhang** [comment]
谢谢！

**Comment by messense** [comment]
哈哈，我来安利一下 https://github.com/messense/wechatpy

**Comment by DiroKate** [comment]
我也遇到这个问题，请问具体是怎么解决的？我在这里没有看到解决方案啊

**Comment by whtsky** [comment]
@DiroKate 可以升级到 1.0 版本。
文档参考 http://werobot.readthedocs.io/zh_CN/v1.0.0/start.html#id2
