### ISSUE TITLE
机器人接收模板消息回馈时出错

### ISSUE THREAD

**Issue by aetherwu** [whtsky/WeRoBot#92]
"POST /verify?signature=0669dc85195875fb8d184743a7e7dc87dca801c2&timestamp=1455079233&nonce=1056749328 HTTP/1.0" 500 -

Traceback (most recent call last):
  File "/root/wechat/flask/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/wechat/flask/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/root/wechat/flask/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/wechat/flask/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/wechat/flask/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/wechat/flask/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/wechat/flask/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/wechat/flask/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/wechat/flask/lib/python2.7/site-packages/flask_werobot.py", line 95, in handler
    reply = self.get_reply(message)
  File "/root/wechat/flask/lib/python2.7/site-packages/werobot/robot.py", line 207, in get_reply
    handlers = self.get_handlers(message.type)
  File "/root/wechat/flask/lib/python2.7/site-packages/werobot/robot.py", line 193, in get_handlers
    return self._handlers[type] + self._handlers['all']
KeyError: u'templatesendjobfinish'

根据微信文档，此时投递的信息格式为：

```
<xml>
<ToUserName><![CDATA[gh_7f083739789a]]></ToUserName>
<FromUserName><![CDATA[oia2TjuEGTNoeX76QEjQNrcURxG8]]&g;</FromUserName>
<CreateTime>1395658920</CreateTime>
<MsgType><![CDATA[event]]></MsgType>
<Event><![CDATA[TEMPLATESENDJOBFINISH]]></Event>
<MsgID>200163836</MsgID>
<Status><![CDATA[success]]></Status>
</xml>
```

**Comment by aetherwu** [comment]
微信投递来的信息没错。
但是不知为啥解析出来之后是 message.type 变成了  templatesendjobfinish

**Comment by aetherwu** [comment]
好吧，本来想 Push ，结果发现好像……dev 上的改动挺多的，我也懒得动手了。。。

简单说一下我的做法。

robot.py 的 message_types 增加了 events
```
message_types = ['subscribe', 'unsubscribe', 'click',  'view',  # event
                     'text', 'image', 'link', 'location', 'voice']
                     'text', 'image', 'link', 'location', 'voice', 'events', 'event']
```

然后下面加了冗余的 def events:

 ```
def events(self, f):
        """
        Decorator to add a handler function for ``events`` messages
        """
        self.add_handler(f, type='events')
        return f
```

这样做也许有点儿脏，但貌似管用。
返回了「正常」的 message object：

`{
'Status': u'success', 
'FromUserName': u'o05FYxFr7xXwx6wy1xZfBhtoRruI', 
'MsgID': u'401794236', 
'ToUserName': u'gh_dbf929995944', 
'CreateTime': u'1455112912',
'raw': '<xml><ToUserName><![CDATA[gh_dbf929995944]]></ToUserName>\n<FromUserName><![CDATA[o05FYxFr7xXwx6wy1xZfBhtoRruI]]></FromUserName>\n<CreateTime>1455112912</CreateTime>\n<MsgType><![CDATA[event]]></MsgType>\n<Event><![CDATA[TEMPLATESENDJOBFINISH]]></Event>\n<MsgID>401794236</MsgID>\n<Status><![CDATA[success]]></Status>\n</xml>', 
'type': u'event', 
'Event': u'TEMPLATESENDJOBFINISH'
}
`

在当前的 master 版本里，最后两行不见了。

在 Flask 里的调用就是

```
@robot.events
def replyevent(message):
	return True
```

虽然并不影响使用，但看着后台报错不能忍。。。

**Comment by whtsky** [comment]
之前写代码的时候没有考虑到扩展性，现在准备重构 Event 相关的代码……

**Comment by aetherwu** [comment]
@whtsky 
期盼：） 
期望可以支付、事件部分都可以集成在一起最好了。
通过阅读你的代码学习到很多的东西。
